"""add_session_metrics_columns

Revision ID: e2e697f683f7
Revises: d051336af1c2
Create Date: 2026-05-04 05:57:39.680204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e697f683f7'
down_revision: Union[str, None] = 'd051336af1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('libre_session_uploads', sa.Column('distance_meters', sa.Float(), nullable=True))
    op.add_column('libre_session_uploads', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('libre_session_uploads', sa.Column('stroke_count', sa.Integer(), nullable=True))
    op.add_column('libre_session_uploads', sa.Column('avg_spm', sa.Float(), nullable=True))
    op.add_column('libre_session_uploads', sa.Column('max_speed', sa.Float(), nullable=True))
    op.add_column('libre_session_uploads', sa.Column('avg_speed', sa.Float(), nullable=True))
    op.add_column('libre_session_uploads', sa.Column('has_gps', sa.Boolean(), nullable=True))
    op.add_column('libre_session_uploads', sa.Column('paddlers_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('libre_session_uploads', 'paddlers_count')
    op.drop_column('libre_session_uploads', 'has_gps')
    op.drop_column('libre_session_uploads', 'avg_speed')
    op.drop_column('libre_session_uploads', 'max_speed')
    op.drop_column('libre_session_uploads', 'avg_spm')
    op.drop_column('libre_session_uploads', 'stroke_count')
    op.drop_column('libre_session_uploads', 'duration_seconds')
    op.drop_column('libre_session_uploads', 'distance_meters')
    # ### end Alembic commands ###
